### PR TITLE
Dimming fix

### LINKED ISSUE #16: Image dimming
Somewhere and somehow because of specular lighting whole image, including blank part becomes darker

### PR DESCRIPTION
**Pull request by andylvua**
The problem was caused by improper calculation of the maximum color in the image. This issue has been fixed - closes #16. Also, a simple refactoring and improved implementations of some methods were made.

### CODE REVIEW

File: src/app/image.cpp [hunk 1]
```diff
@@ -103,36 +112,22 @@ int Image::getHeight() const {
...
-            }
+            max_red = std::max(max_red, r_channel_m[x][y]);
+            max_green = std::max(max_green, g_channel_m[x][y]);
+            max_blue = std::max(max_blue, b_channel_m[x][y]);
         }
     }
-}
\ No newline at end of file
+
+    double max_color = std::max({max_red, max_green, max_blue});
```
Comment (codefloww) [inline src/app/image.cpp:128]: Huh? Missed header `algorithm`

Comment (andylvua) [reply src/app/image.cpp:128]: Fixed in 73c9e85

**Review by codefloww — APPROVED** [review]
This pull request looks so good for me that I am ready to buy shawarma for the author
